# Use golang:1.22 as the builder stage
FROM golang:1.22 as builder

# Use Alpine Linux as the base image for the final stage
FROM alpine:latest

# # Install Gradle and Java using apk
RUN apk update && \
    apk add --no-cache openjdk11 && \
    apk add --no-cache gradle

# Copy the built Go executable from the builder stage to the final stage
COPY release/linux/arm64/drone-gradle-plugin /bin/

# Set the entrypoint to the Go executable
ENTRYPOINT ["/bin/drone-gradle-plugin"]
